version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: marketing_analytics
      POSTGRES_USER: marketing_user
      POSTGRES_PASSWORD: marketing_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketing_user -d marketing_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Marketing Analytics Application
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-for-docker
      - JWT_SECRET_KEY=your-jwt-secret-for-docker
      - DATABASE_URL=postgresql://marketing_user:marketing_password@db:5432/marketing_analytics
      - PORT=5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mount for development (optional - comment out for production)
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: 