services:
  - type: web
    name: marketing-analytics-platform
    env: docker
    healthCheckPath: /api/v1/health
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketing-analytics-db
          property: connectionString
      - key: PORT
        value: 5000

databases:
  - name: marketing-analytics-db
    databaseName: marketing_analytics
    user: marketing_user 