services:
  - type: web
    name: marketing-analytics-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    healthCheckPath: /api/v1/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketing-analytics-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://marketing-analytics-frontend.vercel.app

databases:
  - name: marketing-analytics-db
    databaseName: marketing_analytics
    user: marketing_user 